In [4]:
#Array Operations

In [5]:
import numpy as np

In [6]:
#Arithmatic operations

In [7]:
a1 = np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [8]:
a1+a2 #to perform opeartions array size must be same

array([ 7,  9, 11, 13, 15])

In [9]:
a2-a1

array([5, 5, 5, 5, 5])

In [10]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [11]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [12]:
a1//a2

array([0, 0, 0, 0, 0])

In [13]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [14]:
#BroadCasting

In [15]:
import numpy as np
l = [10,20,30,40]
arr=np.array(l)

In [16]:
arr+10 #this is the concept of broadcasting wwhen u want to add to all the elemnts

array([20, 30, 40, 50])

In [17]:
#Deep and Shallow Copy

In [18]:
 a = np.arange(1,21)
 a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
slice = a[:5]
slice=slice*10

In [20]:
slice

array([10, 20, 30, 40, 50])

In [21]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
b=a.copy()

In [23]:
b[0]=99

In [24]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
#Matrix Operations

In [29]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [30]:
a*b

array([[ 5, 12],
       [21, 32]])

In [31]:
a@b #real matrix multiplication

array([[19, 22],
       [43, 50]])

In [32]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [33]:
a.T # mtaarix transpose

array([[1, 3],
       [2, 4]])

In [34]:
a

array([[1, 2],
       [3, 4]])

In [35]:
#Advanced Array Manipulation

In [36]:
#Stacking Array

In [42]:
a =np.array([1,2,3,4])
b= np.array([5,6,7,8])

In [45]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [49]:
#Splitting Array

In [51]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
np.hsplit(c,2)

In [59]:
a=np.vsplit(c,4)

In [60]:
for i in a:
  print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
