In [ ]:
#Array Operations

In [ ]:
import numpy as np

In [ ]:
#Arithmatic operations

In [ ]:
a1 = np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [ ]:
a1+a2 #to perform opeartions array size must be same

array([ 7,  9, 11, 13, 15])

In [ ]:
a2-a1

array([5, 5, 5, 5, 5])

In [ ]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [ ]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a1//a2

array([0, 0, 0, 0, 0])

In [ ]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
#BroadCasting

In [ ]:
import numpy as np
l = [10,20,30,40]
arr=np.array(l)

In [ ]:
arr+10 #this is the concept of broadcasting wwhen u want to add to all the elemnts

array([20, 30, 40, 50])

In [ ]:
#Deep and Shallow Copy

In [ ]:
 a = np.arange(1,21)
 a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice = a[:5]
slice=slice*10

In [ ]:
slice

array([10, 20, 30, 40, 50])

In [ ]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
b=a.copy()

In [ ]:
b[0]=99

In [ ]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#Matrix Operations

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [ ]:
a*b

array([[ 5, 12],
       [21, 32]])

In [ ]:
a@b #real matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [ ]:
a.T # mtaarix transpose

array([[1, 3],
       [2, 4]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
#Advanced Array Manipulation

In [ ]:
#Stacking Array

In [ ]:
a =np.array([1,2,3,4])
b= np.array([5,6,7,8])

In [ ]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
#Splitting Array

In [ ]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
a=np.vsplit(c,4)

In [ ]:
for i in a:
  print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


In [ ]:
#NUMPY EXERCISES

In [ ]:
#valid SUDOKU

In [ ]:
import numpy as np

In [ ]:
s=np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

In [ ]:
#suduko is valid when its sum comes 45 for each row and col
#and also valid when its 3*3 matrix sum also should comes as 45

In [ ]:
b=np.sum(s,axis=1)#rows axis is 1 for sum
b

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
#another way for rows using loop
for i in b:
  if i !=45:
    print("not valid sudoku")
else:
  print("valid Sudoku")

valid Sudoku


In [ ]:
#now for doing cloumns
c=np.sum(s,axis=0)#columns axis =1 for sum
c

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
c==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
#another way for rows using loop
for i in c:
  if i !=45:
    print("not valid sudoku")
else:
  print("valid Sudoku")

valid Sudoku


In [ ]:
#now checking suduko for 3*3 matrix
for i in range(0,9,3):
  for j in range(0,9,3):
    n=s[i:i+3,j:j+3]
    print(n.sum())

45
45
45
45
45
45
45
45
45


In [ ]:
#Some General Questions of NUMPY ARRAY

In [ ]:
# columns[AGE,MATH MARKS,SCIENCE MARKS]
data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,78],
    [20,90,85]
    ])

In [ ]:
np.mean(data[:,0]) # avg of age

np.float64(18.4)

In [ ]:
data[:,1] #extracting maths marks of all studnets

array([85, 92, 76, 65, 90])

In [ ]:
np.max(data[:,2]) #getting highest science marks

np.int64(95)

In [ ]:
# get details of student who scored more than 90 in maths
data[data[:,1] > 90]

array([[19, 92, 88]])

In [ ]:
#increase  maths marks of all students by 5
data[:,1] + 5

array([90, 97, 81, 70, 95])

In [ ]:
#find how many students are yonger than 19
len(data[data[:,0] < 19])

3

In [ ]:
#calculate the avg marks of each subject(col-wise mean)
np.mean(data[:,1:3],axis=0)

array([81.6, 84.8])

In [ ]:
#get data of students who scored at least 80 in both subjects
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [ ]:
#replace all science marks < 75 with 0
data[:,2][data[:,2] < 75]=0

In [ ]:
data

array([[18, 85,  0],
       [19, 92,  0],
       [17, 76,  0],
       [18, 65,  0],
       [20, 90,  0]])