In [1]:
import numpy as np

In [2]:
#Numpy Indexing And slicing Of Vectors

In [3]:
arr=np.arange(11,21)
print(arr)

[11 12 13 14 15 16 17 18 19 20]


In [4]:
arr[6]

np.int64(17)

In [5]:
#slicing is like removing a portion or dealing with subarray

In [6]:
arr[1:5]

array([12, 13, 14, 15])

In [7]:
 #Numpy Indexing And Slicing Of Matrix

In [8]:
arr=np.arange(1,31)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [9]:
arr=arr.reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [10]:
arr[0]

array([1, 2, 3, 4, 5])

In [11]:
arr[1][0]

np.int64(6)

In [12]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [13]:
arr[0:2,1:4]


array([[2, 3, 4],
       [7, 8, 9]])

In [14]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [15]:
#Boolean Indexing

In [16]:
arr = np.arange(10,20)

In [17]:
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [18]:
bool_index=arr%2==0

In [19]:
bool_index

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [20]:
arr= arr[bool_index]

In [21]:
arr # false values are reomved only true values are left

array([10, 12, 14, 16, 18])