In [ ]:
import numpy as np

In [ ]:
#Basic Array Creation

In [ ]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
a =[1,2,3,4,"hello"]
print(a)

[1, 2, 3, 4, 'hello']


In [ ]:
l=[[1,2,3,],[2,5,6]]
np.array(l)

array([[1, 2, 3],
       [2, 5, 6]])

In [ ]:
#Array Generation Function

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
arr=np.zeros((3,3))

In [ ]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#random generation function

In [ ]:
np.random.randint(10,20,10)

array([17, 10, 12, 11, 18, 10, 19, 18, 13, 12])

In [ ]:
np.random.rand(10)

array([0.14973255, 0.06407822, 0.78824378, 0.10477016, 0.49425516,
       0.67581059, 0.75973733, 0.16713725, 0.07542017, 0.08327104])

In [ ]:
np.random.randn(10)

array([-0.9402721 ,  1.00087363,  0.52221212,  0.63364222,  0.760183  ,
       -0.4195203 ,  0.76133696, -1.94969134,  0.36217554, -0.22994669])

In [ ]:
#Array attributes

In [ ]:
arr=np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
#Array Methods

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.min()


np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis=0)#col wise sum

array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1)# row wise sum

array([ 6, 15, 24])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

In [ ]:
#Reshaping and Resizing

In [ ]:
arr=np.arange(1,31)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [ ]:
arr=arr.reshape(6,5)

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])